name: vue-admin-api
services:
  mysql:
    container_name: mysql
    networks:
      - vue-admin-api-network
    image: mysql:8.3.0
    command: --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
    environment:
      - MYSQL_ROOT_PASSWORD=vue-admin-api
      - MYSQL_LOWER_CASE_TABLE_NAMES=0
    ports:
      - '3306:3306'
    volumes:
      - ./data/mysql:/var/lib/mysql
  redis:
    container_name: redis
    networks:
      - vue-admin-api-network
    image: redis:7.4
    ports:
      - '6379:6379'
    volumes:
      - ./data/redis:/data
  rabbitmq:
    container_name: rabbitmq
    networks:
      - vue-admin-api-network
    image: rabbitmq:4.0-management
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq # 持久化数据
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: 123456
networks:
  vue-admin-api-network:
    driver: bridge
